apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-acl
  namespace: redis
data:
  users.acl: |
    # user "default" is the default user ( act as admin ) and user "replication" is used by the nodes for the replication.
    user default on #8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918 ~* &* +@all
    user replication on #65cf6f5f48186a4a6c5de02f156f1642b3873451d9de1607147799023dbf4ef8 +psync +replconf +ping
    user worker on #87eba76e7f3164534045ba922e7770fb58bbd14ad732bbf5ba6f11cc56989e6e ~* &* +@all -@dangerous
